name: CI

on: 
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Python ${{ matrix.version }}
    strategy: 
      matrix:
        version: [2.7, 3.6, 3.8, 3.9]

    steps: 
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: | 
          python setup.py install
      - name: Run Tests
        run: python setup.py test
